/* Automatic generated by cd-cli */
import Vue from 'vue'
import Router from 'vue-router'
Vue.use(Router);

let routes = [
{
  path: '/main',
  name: 'main',
  component: resolve => {
    require.ensure([], () => {
      resolve(require('../../page/main/main.vue'))
    }, 'main')
  }
}
];

import _base from './base';
routes = routes.concat(_base);

export default new Router({routes})
